// Built-in question deck. Questions are phrased so the answer is one of the
// two players ("who ..."), matching the shoe-game format. Deliberately light
// on the clichés found in every wedding listicle. Most of these are
// "thinkers": oddly specific habits, hypotheticals with stakes, perception
// gaps the couple will disagree on, and shared-history re-litigation.
// Gender-neutral throughout so any couple can play.

export const DECK: string[] = [
  // Warm-ups (a few classics to get the shoes moving)
  'Who is the better cook?',
  'Who takes longer to get ready?',
  'Who said "I love you" first?',
  'Who is the better driver?',
  'Who falls asleep first?',
  'Who is more stubborn?',
  'Who is the funnier one?',
  'Who hogs the blanket?',
  'Who is the messier one?',
  'Who is more addicted to their phone?',
  'Who is more competitive?',
  'Who is more patient?',
  'Who is the early bird?',
  'Who is more romantic?',
  'Who snores the loudest?',
  'Who is grumpier before their morning coffee?',
  'Who owns more shoes? (Fitting, right?)',
  'Who loves the other more? (Careful now!)',

  // Domestic chaos, oddly specific
  'Who would notice the milk expired three days ago and drink it anyway?',
  'Who secretly rearranges the dishwasher after the other one has loaded it?',
  'Who would eat the last slice and blame it on a ghost?',
  'Who lets the "check engine" light become a permanent dashboard decoration?',
  'Who narrates the pet\'s inner thoughts in a full character voice?',
  'Who keeps a drawer of chargers that fit absolutely nothing you own?',
  'Who would find a spider, shriek, then insist they were "just startled"?',
  'Who reheats the same cup of coffee four times and never finishes it?',
  'Who argues out loud with the GPS as if it can hear them?',
  'Who leaves one square on the roll to avoid replacing the toilet paper?',
  'Who starts reorganizing a cupboard and leaves it worse than before?',
  'Who saves the last bite, hoping the other forgets it exists?',
  'Who treats the bedroom floor as a personal laundry basket?',
  'Who is more likely to burn the house down making dinner?',
  'Who would name a houseplant and genuinely grieve when it dies?',
  'Who would argue out loud with a self-checkout machine?',
  'Who apologizes to furniture after bumping into it?',

  // Hypotheticals with stakes
  'Who would crack first and confess everything under police interrogation?',
  'Who is more likely to talk their way out of an arrest with a smile?',
  'Who would actually need bailing out of jail first?',
  'Who is more likely to accidentally start a cult without meaning to?',
  'Who would blow through a lottery win faster?',
  'Who would still show up to work the day after becoming a billionaire?',
  'Who would survive a whole week pretending to be the other person?',
  'Who would befriend the villain in any situation?',
  'Who would turn into a full-blown villain if handed real power?',
  'Who would cave first if a genie offered a shortcut with a catch?',
  'Who would chase down the cashier to return change given by mistake?',
  'Who would risk more to protect a complete stranger?',
  'Who would hand a stranger their last £20 without thinking twice?',
  'Who would text a scammer back just to be polite?',
  'Who would sell the other to aliens for a quiet, comfortable life?',
  'Who would survive longer on a deserted island?',
  'Who would survive longer in a zombie apocalypse?',
  'Who would fake a small emergency to leave a party early?',
  'Who is the better liar? (Think carefully…)',

  // Perception gaps, where the fun is that you'll disagree
  'Who thinks they always win arguments, and who actually does?',
  'Who is more convinced they\'re the reasonable one in every disagreement?',
  'Who secretly believes they\'re the more attractive one?',
  'Who thinks their taste in music is simply, objectively correct?',
  'Who believes they\'re a far better dancer than the evidence suggests?',
  'Who wildly overestimates how good their own advice is?',
  'Who is more likely to say "I\'m not mad" while clearly being mad?',
  'Who is convinced they\'re the low-maintenance one?',
  'Who assumes they\'d win a fight but absolutely would not?',
  'Who is more convinced that they\'re always the calm one?',
  'Who is most likely to be bending the truth during this very game?',
  'Who says "I don\'t mind, you choose" and then vetoes every choice?',
  'Who says "we\'ll see" and means an absolute no?',
  'Who tells a story that\'s technically true but wildly exaggerated?',
  'Who is the real reason you\'re always ten minutes late?',
  'Who overpromises, and who quietly does the actual work?',
  'Who would accidentally take credit for the other\'s idea?',
  'Who is more likely to correct the other mid-story in front of guests?',
  'Who gives the worse gift but is more sure it\'s a masterpiece?',
  'Who is more likely to google a mild symptom and decide they\'re dying?',
  'Who is more likely to cry at a stranger\'s wedding on TV?',
  'Who reads reviews for 45 minutes before buying a £5 gadget?',
  'Who rehearses arguments in the shower and still loses the real one?',
  'Who plans the itinerary for a holiday you haven\'t even booked?',
  'Who is more likely to cry at this game?',

  // Relationship archaeology: re-litigate your own history
  'Who remembers the details of your first date more accurately?',
  'Who fell for the other first but won\'t admit it?',
  'Who honestly caused your very first real argument?',
  'Who tells the story of how you met with more exaggeration?',
  'Who was more nervous the first time they met the other\'s family?',
  'Who caved and apologized first after your biggest fight?',
  'Who actually made the first move (no revisionist history allowed)?',
  'Who still owes the other an apology from years ago?',
  'Who secretly kept more mementos from when you first started dating?',
  'Who has changed the most since the day you met?',
  'Who holds a grudge from a fight the other doesn\'t even remember?',
  'Who remembers every past argument like a court transcript?',
  'Who forgives faster after a genuine fight?',
  'Who apologizes first, even when they\'re the one who\'s right?',
  'Who would win a debate about whose family is weirder?',
  'Who would each of your mothers secretly side with?',
  'Who would your friends call first with good news?',
  'Who is the emergency contact the other actually wants?',
  'Who stalked the other online first?',
  'Who is the better kisser? (You have to answer!)',

  // Future-projection with a twist
  'Who will become the embarrassing parent dancing at school drop-off?',
  'Who will retire and instantly take up a chaotic new hobby?',
  'Who will be the one shushing everyone in the quiet retirement village?',
  'Who will spoil your future pet into a tiny household tyrant?',
  'Who will still be telling the same story at your 50th anniversary?',
  'Who will insist the loudest that they\'re "not old" at sixty?',
  'Who will get weirdly territorial about the thermostat in old age?',
  'Who will be the grandparent sneaking the kids extra dessert?',
  'Who will still be losing their keys when you\'re eighty?',
  'Who will be first to suggest moving somewhere with zero neighbours?',
  'Who will be the strict one with kids or pets?',
  'Who will still be playing this game at 80?',
  'Who is secretly the soft romantic hiding under all the sarcasm?',
  'Who would notice first if the other came home with a new haircut?',
  'Who plans the surprise, and who accidentally ruins it?',
  'Who is still talking long after the other has fallen asleep?',
  'Who is the real boss of this relationship? (Diplomacy time!)',
];

export function randomQuestion(exclude: Set<string> = new Set()): string {
  const available = DECK.filter((q) => !exclude.has(q));
  const pool = available.length > 0 ? available : DECK;
  return pool[Math.floor(Math.random() * pool.length)];
}
