// Built-in question deck. Every question is phrased so the answer is one of
// the two players ("who ..."), matching the shoe-game format. Light on the
// clichés from every wedding listicle: most are thinkers, oddly specific
// habits, hypotheticals with stakes, perception gaps the couple will disagree
// on, and shared-history re-litigation. Gender-neutral throughout.
//
// Questions are grouped into flavours so the asker can steer the mood. The
// client shows these as chips; "any" draws from the whole deck.

export const FLAVOURS = [
  { id: 'classic', label: 'Warm-ups', emoji: '👋' },
  { id: 'home', label: 'At home', emoji: '🏠' },
  { id: 'whatif', label: 'What if', emoji: '🎲' },
  { id: 'self', label: 'Self-image', emoji: '🪞' },
  { id: 'story', label: 'Our story', emoji: '📖' },
  { id: 'future', label: 'Someday', emoji: '🔮' },
  { id: 'bigday', label: 'Big day', emoji: '💒' },
  { id: 'out', label: 'Out & about', emoji: '🧳' },
  { id: 'money', label: 'Money & work', emoji: '💸' },
  { id: 'spicy', label: 'A bit spicy', emoji: '🌶️' },
] as const;

export type Flavour = (typeof FLAVOURS)[number]['id'];

export interface Question {
  text: string;
  flavour: Flavour;
}

export function flavourInfo(id: Flavour) {
  return FLAVOURS.find((f) => f.id === id) ?? FLAVOURS[0];
}

const group = (flavour: Flavour, texts: string[]): Question[] => texts.map((text) => ({ text, flavour }));

export const DECK: Question[] = [
  ...group('classic', [
    'Who is the better cook?',
    'Who takes longer to get ready?',
    'Who said "I love you" first?',
    'Who is the better driver?',
    'Who falls asleep first?',
    'Who is more stubborn?',
    'Who is the funnier one?',
    'Who hogs the blanket?',
    'Who is the messier one?',
    'Who is more addicted to their phone?',
    'Who is more competitive?',
    'Who is more patient?',
    'Who is the early bird?',
    'Who is more romantic?',
    'Who snores the loudest?',
    'Who is grumpier before their morning coffee?',
    'Who owns more shoes? (Fitting, right?)',
    'Who loves the other more? (Careful now!)',
    'Who is the better listener?',
    'Who is more likely to lose their keys today?',
    'Who has the louder laugh?',
    'Who is the bigger foodie?',
  ]),

  ...group('home', [
    'Who would notice the milk expired three days ago and drink it anyway?',
    'Who secretly rearranges the dishwasher after the other one has loaded it?',
    'Who would eat the last slice and blame it on a ghost?',
    'Who lets the "check engine" light become a permanent dashboard decoration?',
    "Who narrates the pet's inner thoughts in a full character voice?",
    'Who keeps a drawer of chargers that fit absolutely nothing you own?',
    'Who would find a spider, shriek, then insist they were "just startled"?',
    'Who reheats the same cup of coffee four times and never finishes it?',
    'Who argues out loud with the GPS as if it can hear them?',
    'Who leaves one square on the roll to avoid replacing the toilet paper?',
    'Who starts reorganizing a cupboard and leaves it worse than before?',
    'Who saves the last bite, hoping the other forgets it exists?',
    'Who treats the bedroom floor as a personal laundry basket?',
    'Who is more likely to burn the house down making dinner?',
    'Who would name a houseplant and genuinely grieve when it dies?',
    'Who would argue out loud with a self-checkout machine?',
    'Who apologizes to furniture after bumping into it?',
    'Who has strong opinions about the correct way to hang the toilet roll?',
    'Who "helps" with DIY by holding the torch in the wrong place?',
    'Who changes the thermostat the moment the other leaves the room?',
    'Who puts an empty container back in the fridge?',
    'Who could sit on a brand new cushion for a week without noticing it was new?',
    'Who leaves a cupboard door open in every room they walk through?',
    'Who buys a gadget for the kitchen and uses it exactly once?',
    'Who would rather buy new socks than pair the ones in the drawer?',
    'Who treats "I will do it later" as a legally binding schedule?',
  ]),

  ...group('whatif', [
    'Who would crack first and confess everything under police interrogation?',
    'Who is more likely to talk their way out of an arrest with a smile?',
    'Who would actually need bailing out of jail first?',
    'Who is more likely to accidentally start a cult without meaning to?',
    'Who would blow through a lottery win faster?',
    'Who would still show up to work the day after becoming a billionaire?',
    'Who would survive a whole week pretending to be the other person?',
    'Who would befriend the villain in any situation?',
    'Who would turn into a full-blown villain if handed real power?',
    'Who would cave first if a genie offered a shortcut with a catch?',
    'Who would chase down the cashier to return change given by mistake?',
    'Who would risk more to protect a complete stranger?',
    'Who would hand a stranger their last £20 without thinking twice?',
    'Who would text a scammer back just to be polite?',
    'Who would sell the other to aliens for a quiet, comfortable life?',
    'Who would survive longer on a deserted island?',
    'Who would survive longer in a zombie apocalypse?',
    'Who would fake a small emergency to leave a party early?',
    'Who is the better liar? (Think carefully.)',
    'Who would win a quiz show that was only trivia?',
    'Who would be voted off a reality show first?',
    'Who would last a full night in a haunted house without leaving?',
    'Who would eat a bug for a hundred pounds?',
    'Who would make the better spy?',
    'Who would be the getaway driver in a heist?',
    'Who would keep a found wallet for a day "just to think about it"?',
    'Who would adopt a stray on the way home from the shop?',
    'Who would accidentally join a pyramid scheme through a friend?',
    'Who would panic first if the internet went down for a week?',
    'Who would win if you both swapped jobs for a month?',
  ]),

  ...group('self', [
    'Who thinks they always win arguments, and who actually does?',
    "Who is more convinced they're the reasonable one in every disagreement?",
    "Who secretly believes they're the more attractive one?",
    'Who thinks their taste in music is simply, objectively correct?',
    "Who believes they're a far better dancer than the evidence suggests?",
    'Who wildly overestimates how good their own advice is?',
    'Who is more likely to say "I\'m not mad" while clearly being mad?',
    "Who is convinced they're the low-maintenance one?",
    "Who assumes they'd win a fight but absolutely would not?",
    "Who is more convinced that they're always the calm one?",
    'Who is most likely to be bending the truth during this very game?',
    'Who says "I don\'t mind, you choose" and then vetoes every choice?',
    'Who says "we\'ll see" and means an absolute no?',
    "Who tells a story that's technically true but wildly exaggerated?",
    "Who is the real reason you're always ten minutes late?",
    'Who overpromises, and who quietly does the actual work?',
    "Who would accidentally take credit for the other's idea?",
    'Who is more likely to correct the other mid-story in front of guests?',
    "Who gives the worse gift but is more sure it's a masterpiece?",
    "Who is more likely to google a mild symptom and decide they're dying?",
    "Who is more likely to cry at a stranger's wedding on TV?",
    'Who reads reviews for 45 minutes before buying a £5 gadget?',
    'Who rehearses arguments in the shower and still loses the real one?',
    "Who plans the itinerary for a holiday you haven't even booked?",
    'Who is more likely to cry at this game?',
    'Who thinks they are the better texter?',
    'Who thinks they are the punctual one?',
    'Who insists they never snore?',
    'Who thinks they could fix the wifi but has never once fixed the wifi?',
    'Who believes they have a great poker face?',
    'Who thinks they are the one who compromises more?',
  ]),

  ...group('story', [
    'Who remembers the details of your first date more accurately?',
    "Who fell for the other first but won't admit it?",
    'Who honestly caused your very first real argument?',
    'Who tells the story of how you met with more exaggeration?',
    "Who was more nervous the first time they met the other's family?",
    'Who caved and apologized first after your biggest fight?',
    'Who actually made the first move (no revisionist history allowed)?',
    'Who still owes the other an apology from years ago?',
    'Who secretly kept more mementos from when you first started dating?',
    'Who has changed the most since the day you met?',
    "Who holds a grudge from a fight the other doesn't even remember?",
    'Who remembers every past argument like a court transcript?',
    'Who forgives faster after a genuine fight?',
    "Who apologizes first, even when they're the one who's right?",
    'Who would win a debate about whose family is weirder?',
    'Who would each of your mothers secretly side with?',
    'Who would your friends call first with good news?',
    'Who is the emergency contact the other actually wants?',
    'Who stalked the other online first?',
    'Who is the better kisser? (You have to answer!)',
    "Who saved the other's number under a nickname first?",
    'Who pretended to like a hobby to impress the other?',
    "Who was the first to leave a toothbrush at the other's place?",
    'Who has the worse memory for your anniversaries?',
    'Who was more sure, sooner, that this was it?',
    'Who talked about the other more to their friends in the first month?',
    'Who had the worse outfit on your first date?',
    'Who was the first to say "we" instead of "I" in a story?',
  ]),

  ...group('future', [
    'Who will become the embarrassing parent dancing at school drop-off?',
    'Who will retire and instantly take up a chaotic new hobby?',
    'Who will be the one shushing everyone in the quiet retirement village?',
    'Who will spoil your future pet into a tiny household tyrant?',
    'Who will still be telling the same story at your 50th anniversary?',
    'Who will insist the loudest that they\'re "not old" at sixty?',
    'Who will get weirdly territorial about the thermostat in old age?',
    'Who will be the grandparent sneaking the kids extra dessert?',
    "Who will still be losing their keys when you're eighty?",
    'Who will be first to suggest moving somewhere with zero neighbours?',
    'Who will be the strict one with kids or pets?',
    'Who will still be playing this game at 80?',
    'Who is secretly the soft romantic hiding under all the sarcasm?',
    'Who would notice first if the other came home with a new haircut?',
    'Who plans the surprise, and who accidentally ruins it?',
    'Who is still talking long after the other has fallen asleep?',
    'Who is the real boss of this relationship? (Diplomacy time!)',
    'Who will insist the kids learn an instrument they never learned themselves?',
    'Who will become obsessed with the garden overnight?',
    'Who will refuse to replace a phone from 2035 because "it still works"?',
    'Who will be the one who writes the family group chat rules?',
    'Who will start a tradition that nobody else asked for?',
    'Who will forget where the car is parked more often in twenty years?',
    'Who will be the parent that the teacher wants to talk to?',
  ]),

  ...group('bigday', [
    'Who will cry first during the vows?',
    'Who will forget the words to the vows they wrote themselves?',
    'Who will lose a relative somewhere in the venue and only notice at the speeches?',
    'Who is more likely to spill something on their outfit before the photos?',
    'Who will sneak off to eat first?',
    'Who will still be dancing when the DJ is packing up?',
    'Who will open the gift envelopes and read the cards before counting anything?',
    'Who will be more stressed about the seating chart the night before?',
    'Who needs more reminding that they cannot control the weather?',
    'Who will lose their voice first from singing along at the reception?',
    'Who will give a speech that runs twice as long as planned?',
    'Who will find a way to check their phone during the ceremony?',
    'Who will ask the photographer for just one more picture?',
    'Who will fall asleep first on the wedding night, mid-sentence?',
    'Who will accidentally invite someone the other has never heard of?',
    'Who is more likely to have a wardrobe emergency involving safety pins?',
    'Who will negotiate harder with a vendor?',
    'Who will remember the anniversary date without checking?',
    'Who will be the first to say "we should have eloped"?',
    'Who will tear up watching the other walk in?',
    'Who will be told off by the planner for wandering away?',
    'Who will make friends with the band?',
  ]),

  ...group('out', [
    'Who starts packing in the taxi to the airport?',
    'Who orders the same dish at every restaurant and calls it a classic?',
    "Who steals from the other's plate while insisting they were full?",
    'Who gets you lost and then blames the map?',
    'Who would eat street food from a stall with no visible customers?',
    'Who turns a two-hour drive into a five-hour drive with detours?',
    'Who leaves something behind in every hotel room?',
    'Who is the reason you never make the early flight?',
    'Who orders for the table without asking?',
    'Who complains about the cold and then refuses to wear a jacket?',
    'Who would haggle over a souvenir for twenty minutes to save a pound?',
    'Who picks a restaurant by the smell walking past instead of the reviews?',
    'Who talks to strangers on holiday like they are old friends?',
    'Who takes the window seat without offering?',
    'Who gets sunburnt on day one and insists it does not hurt?',
    'Who needs a snack in the bag at all times, like a toddler?',
    'Who finishes the popcorn before the film has even started?',
    'Who would order dessert first if nobody was watching?',
    'Who says "just going to look" and comes home with three bags?',
    'Who would choose the hotel by its breakfast alone?',
    'Who is more likely to befriend the waiter and get a free dessert?',
    'Who leaves the party early, and who is the last one there?',
    'Who takes forty photos of the same sunset?',
  ]),

  ...group('money', [
    'Who checks the bank balance the morning after a night out?',
    'Who has a subscription they have forgotten about and still pay for?',
    'Who would negotiate a raise more confidently?',
    'Who buys the extended warranty?',
    'Who treats a sale as money saved rather than money spent?',
    'Who would spend the emergency fund on something that is not an emergency?',
    'Who cannot find a receipt from last week but still has a ticket stub from 2016?',
    'Who would draft a five-year plan before quitting a job they hate?',
    'Who would keep a lottery win secret for longer?',
    'Who is more likely to reply to a work email on holiday?',
    'Who would be the better boss?',
    'Who would survive longer without their wallet?',
    'Who would start a business and leave the accounts to the other?',
    'Who has more money hidden in coat pockets right now?',
    'Who tips more generously?',
    'Who pays for the coffee more often and secretly keeps count?',
    'Who would rather have a smaller house and bigger holidays?',
    'Who would notice a wrong charge on the bill first?',
    'Who would lend money to a friend and never bring it up again?',
  ]),

  ...group('spicy', [
    'Who initiates the cuddle and then complains about being too hot?',
    'Who asks for a back rub more often?',
    'Who is the bigger flirt, even now?',
    'Who would win a staring contest without laughing?',
    'Who is more likely to sneak a kiss in front of the in-laws?',
    'Who would be the jealous one if a celebrity flirted with the other?',
    'Who thought about the other more during the first week of dating?',
    'Who is more likely to fall asleep during a romantic film?',
    'Who writes the better love note?',
    'Who has the worse chat-up line?',
    'Who would plan the better date night with a budget of ten pounds?',
    'Who is more likely to whisper something inappropriate at a formal dinner?',
    'Who picks the worse moment for a romantic gesture?',
    'Who takes longer to say goodbye at the door?',
    'Who would blush more if their search history was read aloud?',
    'Who sends the more embarrassing texts?',
    'Who is more likely to have a photo of the other as their lock screen?',
    'Who compliments the other more, and who remembers it longer?',
  ]),
];

/** Pick a random question, skipping any in `exclude`; falls back to the full pool when everything is used. */
export function randomQuestion(exclude: Set<string> = new Set(), flavour: Flavour | 'any' = 'any'): string {
  const pool = flavour === 'any' ? DECK : DECK.filter((q) => q.flavour === flavour);
  const fresh = pool.filter((q) => !exclude.has(q.text));
  const source = fresh.length > 0 ? fresh : pool.length > 0 ? pool : DECK;
  return source[Math.floor(Math.random() * source.length)].text;
}

/** How many unused questions are left in a flavour (or the whole deck). */
export function remaining(exclude: Set<string>, flavour: Flavour | 'any' = 'any'): number {
  const pool = flavour === 'any' ? DECK : DECK.filter((q) => q.flavour === flavour);
  return pool.filter((q) => !exclude.has(q.text)).length;
}
